# Generated by Django 3.1.2 on 2021-01-29 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usernotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_create',
            name='username',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes_create',
            name='note',
            field=models.CharField(max_length=500),
        ),
    ]
